#!C:/Users/prem/AppData/Local/Programs/Python/Python39/python.exe
print("Content-type: text/html \r\n\r\n")
# impotring the common Gateway interface,sql,cgi trackback.
import cgi, pymysql, cgitb;

cgitb.enable()
conn = pymysql.connect(host="localhost", user="root", password="", database="ridesharer")       #connection with phpmysql using Xampp.
cur = conn.cursor()         #To get field data using form
f = cgi.FieldStorage()
id = f.getvalue("id")       #To generate id autogenerated.

if len(f) == 2:         #to get all field details.
    id = f.getvalue("id")
    cid = f.getvalue("cid")
else:
    id = f.getvalue("id")
    cid = f.getvalue("cid")
    name = f.getvalue("name")
    email = f.getvalue("email")
    contact = f.getvalue("contact")
    dob = f.getvalue("dob")
    address = f.getvalue("address")
    username = f.getvalue("username")
    password = f.getvalue("password")
    profile = f['profile']

    if profile.filename:
        import os               #importing operating software.

        fp = os.path.basename(profile.filename)
        open("image/" + fp, "wb").write(profile.file.read())
        # Updating the detals of the clients whish is edited.
        q1 = """update cregistoration set name = '%s',email = '%s',contact = '%s',dob = '%s',address = '%s',username = '%s',password = '%s',profile = '%s' where id = '%s'""" % (
        name, email, contact, dob, address, username, password, fp, cid)
        cur.execute(q1)
        conn.commit()
        #HTML and CSS.
        print("""
             <script>
                alert("Profile updated successfully");
                location.href = "customer.py?id=%s";
            </script>
            """ % (id))
    else:
        q1 = """update cregistoration set name = '%s',email = '%s',contact = '%s',dob = '%s',address = '%s',username = '%s',password = '%s' where id = '%s'""" % (
        name, email, contact, dob, address, username, password, cid)
        cur.execute(q1)
        conn.commit()
        print("""
             <script>
                alert("Profile updated successfully");
                location.href = "customer.py?id=%s";
            </script>
            """ % (id))

q = """select * from cregistoration where id='%s'""" % (cid)
cur.execute(q)
r = cur.fetchone()
#CSS.
print("""
<html>
<head>
    <title>Sharer Registration</title>
    <style>
       body{
            text-align:left;
            padding-left: 40%;
            padding-top:10%;
            background-image:url("images/customer.jfif") ;
            overflow:visible;
        }
        form{
            background: lightcoral;
            width: 30%;
            padding:10px 50px ;
            border-radius: 20px;
        }
    </style>
""")
#HTML
print("""

</head>
<body>
    <h1 style="color:yellow;margin-left:-80px;margin-top:-110px;">CLIENT REGISTORATION FORM</h1>
    <form method = "post" action = "cedit.py" enctype = "multipart/form-data" autocomplete="off>
        <div>
        <input type="hidden" name="id" value="%s">
        <input type="hidden" name="cid" value="%s">
        <label for="name">Name:</label><br>
        <input type="text" id = "name" name="name" placeholder="Enter your name" value="%s"><br><br>
        <label for="email">Mail-Id</label><br>
        <input type="email" id = "email" name="email" placeholder="Enter your email" value="%s"><br><br>
        <label for="contact">Contact:</label><br>
        <input type="tel" id = "contact" name="contact" placeholder="Enter your contact-number" value="%s"><br><br>
        <label for="dob">Age:</label><br>
        <input type="text" id = "dob" name="dob" placeholder="Enter your age" value="%s" ><br><br>
        <label for="address">Address</label><br>
        <input type="text" id = "address" name="address" placeholder="Enter your address" rows="6" cols="30" value="%s"><br><br>
        <label for="username">Username:</label><br>
        <input type="text" id = "username" name="username" value="%s"><br><br>
        <label for="password">Password:</label><br>
        <input type="password" id = "password" name="password" value="%s"><br><br>
        <label for="profile" >Profile:</label><br>
        <img src="images/%s" width="50px" height="50px">
        <input type="file" id = "profile" name="profile"><br><br>
        <button type="submit" name = "reg" id = "reg">Register</button>
        <button type="submit">Cancel</button>
        </div> 
    </form>
</body>
</html>
""" % (id, cid,r[2],r[3],r[6], r[4],r[7], r[8], r[9], r[10]))
conn.close()